### ISSUE TITLE
support export/import of sql seed data

### ISSUE THREAD

**Issue by noandrea** [welance/welance-craft-starter#10]
is there a way to use adminer to load seed data from a file in the `config` folder as it is done for the `schema.yaml` ?

**Comment by ricricucit** [comment]
maybe we could pre-configure this? ![screen shot 2017-09-27 at 17 14 34](https://user-images.githubusercontent.com/1016775/30921719-712c8abc-a3a7-11e7-9f68-62b8e55f7390.png)

**Comment by noandrea** [comment]
doesn’t look like it is possible in the current version of adminer

—
andrea giacobino

**Comment by noandrea** [comment]
maybe it will sometime in the future:

https://github.com/vrana/adminer/pull/229

**Comment by noandrea** [comment]
probably a better approach will be to have a script like the schema - import/export

**Comment by noandrea** [comment]
it is now supported with the the `seed-export.sh` / `seed-import.sh` scripts
