### ISSUE TITLE
change php.ini configuration for max upload size

### ISSUE THREAD

**Issue by noandrea** [welance/welance-craft-starter#15]
default is 2mb, should be set at least 10mb

**Comment by ricricucit** [comment]
hasn't this been done @noandrea ?

**Comment by noandrea** [comment]
yes, but not tested yet on a fresh installation

**Comment by ricricucit** [comment]
I did a fresh install about 2.5 weeks ago.....and I still get the limit set to 2MB

**Comment by ricricucit** [comment]
Actually...where can I change the value on a project I'm currently working on?

**Comment by noandrea** [comment]
there is a workaround for craft2 already committed and it is fixed in the craft3 series
