### ISSUE TITLE
give names to mounted volumes

### ISSUE THREAD

**Issue by ricricucit** [welance/welance-craft-starter#48]
Should we give names to mounted volumes, to avoid ending up into this mess when using `docker volume ls`?

<img width="556" alt="screen shot 2018-03-09 at 15 54 23" src="https://user-images.githubusercontent.com/1016775/37213384-2835c3a6-23b2-11e8-8e5e-8cba00eee713.png">

**Comment by noandrea** [comment]
we could, but it has to be tested since we must make sure that the same volume doesn't get used by two volumes. 

btw, you can use the command `docker volume prune` to remove unused volumes
